# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/greater/greater.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==greater || ORIG_REF_NAME==greater} -quiet] -quiet

# IP: ip/div/div.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div || ORIG_REF_NAME==div} -quiet] -quiet

# IP: ip/exp/exp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exp || ORIG_REF_NAME==exp} -quiet] -quiet

# IP: ip/accu/accu.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accu || ORIG_REF_NAME==accu} -quiet] -quiet

# IP: ip/mult/mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult || ORIG_REF_NAME==mult} -quiet] -quiet

# IP: ip/fix2float_input/fix2float_input.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fix2float_input || ORIG_REF_NAME==fix2float_input} -quiet] -quiet

# IP: ip/L2_ROM/L2_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==L2_ROM || ORIG_REF_NAME==L2_ROM} -quiet] -quiet

# IP: ip/L1_ROM/L1_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==L1_ROM || ORIG_REF_NAME==L1_ROM} -quiet] -quiet

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/MLP/MLP.gen/sources_1/ip/L2_ROM/L2_ROM_ooc.xdc

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/MLP/MLP.gen/sources_1/ip/L1_ROM/L1_ROM_ooc.xdc
