# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/accu/accu.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accu || ORIG_REF_NAME==accu} -quiet] -quiet

# IP: ip/b_ROM0/b_ROM0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==b_ROM0 || ORIG_REF_NAME==b_ROM0} -quiet] -quiet

# IP: ip/mult/mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult || ORIG_REF_NAME==mult} -quiet] -quiet

# IP: ip/a_ROM3/a_ROM3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==a_ROM3 || ORIG_REF_NAME==a_ROM3} -quiet] -quiet

# IP: ip/a_ROM2/a_ROM2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==a_ROM2 || ORIG_REF_NAME==a_ROM2} -quiet] -quiet

# IP: ip/a_ROM1/a_ROM1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==a_ROM1 || ORIG_REF_NAME==a_ROM1} -quiet] -quiet

# IP: ip/exp/exp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exp || ORIG_REF_NAME==exp} -quiet] -quiet

# IP: ip/div/div.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div || ORIG_REF_NAME==div} -quiet] -quiet

# IP: ip/sub/sub.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub || ORIG_REF_NAME==sub} -quiet] -quiet

# IP: ip/fix2float_parameter/fix2float_parameter.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fix2float_parameter || ORIG_REF_NAME==fix2float_parameter} -quiet] -quiet

# IP: ip/SVs_ROM3/SVs_ROM3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SVs_ROM3 || ORIG_REF_NAME==SVs_ROM3} -quiet] -quiet

# IP: ip/SVs_ROM2/SVs_ROM2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SVs_ROM2 || ORIG_REF_NAME==SVs_ROM2} -quiet] -quiet

# IP: ip/SVs_ROM1/SVs_ROM1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SVs_ROM1 || ORIG_REF_NAME==SVs_ROM1} -quiet] -quiet

# IP: ip/fix2float_input/fix2float_input.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fix2float_input || ORIG_REF_NAME==fix2float_input} -quiet] -quiet

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/SVM/SVM.gen/sources_1/ip/b_ROM0/b_ROM0_ooc.xdc

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/SVM/SVM.gen/sources_1/ip/a_ROM3/a_ROM3_ooc.xdc

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/SVM/SVM.gen/sources_1/ip/a_ROM2/a_ROM2_ooc.xdc

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/SVM/SVM.gen/sources_1/ip/a_ROM1/a_ROM1_ooc.xdc

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/SVM/SVM.gen/sources_1/ip/SVs_ROM3/SVs_ROM3_ooc.xdc

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/SVM/SVM.gen/sources_1/ip/SVs_ROM2/SVs_ROM2_ooc.xdc

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/SVM/SVM.gen/sources_1/ip/SVs_ROM1/SVs_ROM1_ooc.xdc
