# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.runs/synth_1/d_control_gripper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.maxThreads 8
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.cache/wt [current_project]
set_property parent.project_path F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files f:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/AM.coe
add_files f:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/CIM.coe
add_files f:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/CM.coe
add_files f:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/IM.coe
read_verilog -library xil_defaultlib -sv {
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/AM.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/CIM.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/CM.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/IM.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/Ngram_input.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/Preprocess.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/add_parallel.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/control_gripper.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/data_recorder.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/divider_parallel.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/float2fix_pdisps.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/float2fix_pfs.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/float2fix_tfs.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/gen_crc.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/gstHD_encoder.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/packet_sender.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/packet_sender_gcmd.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/sensor_decoder.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/slip_inference.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/sqrt_parallel.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/square_parallel.sv
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/d_control_gripper.sv
}
read_verilog -library xil_defaultlib {
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/divider_disp.v
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/float2fix.v
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/mult_disp.v
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/sqrt_disp.v
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/uart_rx.v
  F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/uart_tx.v
}
read_ip -quiet F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.srcs/sources_1/ip/CM_ROM/CM_ROM.xci
set_property used_in_implementation false [get_files -all f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/CM_ROM/CM_ROM_ooc.xdc]

read_ip -quiet F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.srcs/sources_1/ip/AM_ROM/AM_ROM.xci
set_property used_in_implementation false [get_files -all f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/AM_ROM/AM_ROM_ooc.xdc]

read_ip -quiet F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.srcs/sources_1/ip/CIM_ROM/CIM_ROM.xci
set_property used_in_implementation false [get_files -all f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/CIM_ROM/CIM_ROM_ooc.xdc]

read_ip -quiet F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.srcs/sources_1/ip/IM_ROM/IM_ROM.xci
set_property used_in_implementation false [get_files -all f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/IM_ROM/IM_ROM_ooc.xdc]

read_ip -quiet F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.srcs/sources_1/ip/cordic_0/cordic_0.xci

read_ip -quiet F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.srcs/sources_1/ip/div_gen_0/div_gen_0.xci

read_ip -quiet F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci

read_ip -quiet F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.srcs/sources_1/ip/floating_point_0/floating_point_0.xci

read_ip -quiet F:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/d_control_gripper.xdc
set_property used_in_implementation false [get_files F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/d_control_gripper.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top d_control_gripper -part xc7a200tfbg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef d_control_gripper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file d_control_gripper_utilization_synth.rpt -pb d_control_gripper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
