# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/01_SYSU/HDC_Tactile/tactile/code/Verilog5/d_control_gripper/d_control_gripper.xdc

# IP: ip/CM_ROM/CM_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CM_ROM || ORIG_REF_NAME==CM_ROM} -quiet] -quiet

# IP: ip/AM_ROM/AM_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AM_ROM || ORIG_REF_NAME==AM_ROM} -quiet] -quiet

# IP: ip/CIM_ROM/CIM_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CIM_ROM || ORIG_REF_NAME==CIM_ROM} -quiet] -quiet

# IP: ip/IM_ROM/IM_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IM_ROM || ORIG_REF_NAME==IM_ROM} -quiet] -quiet

# IP: ip/cordic_0/cordic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: ip/div_gen_0/div_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: ip/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: ip/floating_point_0/floating_point_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/CM_ROM/CM_ROM_ooc.xdc

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/AM_ROM/AM_ROM_ooc.xdc

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/CIM_ROM/CIM_ROM_ooc.xdc

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/IM_ROM/IM_ROM_ooc.xdc

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/01_SYSU/HDC_Tactile/tactile/code/Artix7/d_control_gripper/d_control_gripper.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
